title: Chaoyue Han's Homepage
page-top-title: Chaoyue Han
top-section-bg-text: Embodied Intelligence & Robotics
home-subtitle: Chaoyue Han | 韩超越 | Zhejiang University
copyright-text: '&copy; Chaoyue Han 2019-2026. All Rights Reserved.'
