title: Chaoyue Han's Homepage
page-top-title: Chaoyue Han
top-section-bg-text:  Electronic Engineering & Mechanization Engineering
home-subtitle: Chaoyue Han | 韩超越 | enfp
copyright-text: '&copy; Chaoyue Han 2019-2025. All Rights Reserved.'
