title: Chaoyue Han's Homepage
page-top-title: Chaoyue Han
top-section-bg-text:  Electronic Engineering & Agricultural Mechanization Engineering
home-subtitle: Chaoyue Han&ensp;|&enfp;韩超越
copyright-text: '&copy; Chaoyue Han 2019-2025. All Rights Reserved.'
